# Maps police.uk force names to the corresponding names used in the police funding dataset.

FORCE_NAME_MAPPING = {
    "Avon and Somerset Constabulary": "Avon & Somerset",
    "Bedfordshire Police": "Bedfordshire",
    "Cambridgeshire Constabulary": "Cambridgeshire",
    "Cheshire Constabulary": "Cheshire",
    "City of London Police": "City of London",
    "Cleveland Police": "Cleveland",
    "Cumbria Constabulary": "Cumbria",
    "Derbyshire Constabulary": "Derbyshire",
    "Devon & Cornwall Police": "Devon & Cornwall",
    "Dorset Police": "Dorset",
    "Durham Constabulary": "Durham",
    "Essex Police": "Essex",
    "Gloucestershire Constabulary": "Gloucestershire",
    "Greater Manchester Police": "Greater Manchester",
    "Hampshire Constabulary": "Hampshire",
    "Hertfordshire Constabulary": "Hertfordshire",
    "Humberside Police": "Humberside",
    "Kent Police": "Kent",
    "Lancashire Constabulary": "Lancashire",
    "Leicestershire Police": "Leicestershire",
    "Lincolnshire Police": "Lincolnshire",
    "Merseyside Police": "Merseyside",
    "Metropolitan Police Service": "Metropolitan Police",
    "Norfolk Constabulary": "Norfolk",
    "North Yorkshire Police": "North Yorkshire",
    "Northamptonshire Police": "Northamptonshire",
    "Northumbria Police": "Northumbria",
    "Nottinghamshire Police": "Nottinghamshire",
    "South Yorkshire Police": "South Yorkshire",
    "Staffordshire Police": "Staffordshire",
    "Suffolk Constabulary": "Suffolk",
    "Surrey Police": "Surrey",
    "Sussex Police": "Sussex",
    "Thames Valley Police": "Thames Valley",
    "Warwickshire Police": "Warwickshire",
    "West Mercia Police": "West Mercia",
    "West Midlands Police": "West Midlands",
    "West Yorkshire Police": "West Yorkshire",
    "Wiltshire Police": "Wiltshire",
}