"""Generate src/data/forceFacts.generated.ts.

Derives two per-force facts the dashboard Overview tab needs but which the main
research snapshot does not carry:

  * Land area in square miles, dissolved from the ONS PFA24 LSOA-joined shapefile
    (reprojected to British National Grid, EPSG:27700).
  * Observed 2025 recorded-crime counts per category, from the police.uk street
    parquet (street_from_2021.parquet, rows where crime_year == 2025).

Run from the research_pipeline directory:

    python scripts/generate_force_facts.py
"""
import json
import re
import sys
from pathlib import Path

import pandas as pd
import geopandas as gpd

PIPELINE = Path(__file__).resolve().parents[1]
ROOT = Path(__file__).resolve().parents[3]
sys.path.insert(0, str(PIPELINE))

from force_name_mapping import FORCE_NAME_MAPPING  # noqa: E402

BACKEND = PIPELINE

# Canonical force names from snapshot
snap = (ROOT / "src/data/researchSnapshot.generated.ts").read_text()
CANON = re.findall(r'"name":\s*"([^"]+)",\s*"netShift"', snap)
CANON_SET = set(CANON)

# --- Area from shapefile (EPSG:27700, meters) ---
PFA_MAP = {"Avon and Somerset": "Avon & Somerset", "London, City of": "City of London"}
g = gpd.read_file(BACKEND / "internal_allocation/lsoaJoinedTerritory/lsoaJoinedTerritory.shp")
g = g.to_crs(epsg=27700)
g["force"] = g["PFA24NM"].map(lambda n: PFA_MAP.get(n, n))
g = g[g["force"].isin(CANON_SET)]
area_m2 = g.dissolve(by="force").geometry.area  # m^2
SQMI = 1 / 2_589_988.110336
area = {f: round(float(a) * SQMI) for f, a in area_m2.items()}

# --- 2025 crime counts by category ---
df = pd.read_parquet(BACKEND / "data/street_from_2021.parquet",
                     columns=["crime_year", "reported_by", "crime_type"])
df = df[df["crime_year"] == 2025]
df["force"] = df["reported_by"].map(FORCE_NAME_MAPPING)
df = df[df["force"].isin(CANON_SET)]
df["crime_type"] = df["crime_type"].fillna("Other crime")
counts = df.groupby(["force", "crime_type"]).size().reset_index(name="n")
crime = {}
for f, sub in counts.groupby("force"):
    crime[f] = {row.crime_type: int(row.n) for row in sub.itertuples()}

facts = {}
for f in CANON:
    facts[f] = {"areaSqMi": area.get(f), "crimeByCategory2025": crime.get(f, {})}

out = ROOT / "src/data/forceFacts.generated.ts"
body = (
    "// AUTO-GENERATED by backend/research_pipeline/scripts/generate_force_facts.py\n"
    "// Per-force land area (sq mi, from ONS PFA24 LSOA-joined shapefile, EPSG:27700)\n"
    "// and observed 2025 crime counts by category (police.uk street_from_2021 parquet).\n"
    "export interface ForceFacts {\n"
    "  areaSqMi: number | null;\n"
    "  crimeByCategory2025: Record<string, number>;\n"
    "}\n\n"
    "export const forceFacts: Record<string, ForceFacts> = "
    + json.dumps(facts, indent=2, ensure_ascii=False)
    + ";\n"
)
out.write_text(body)
print("forces:", len(facts), "| with area:", sum(1 for v in facts.values() if v['areaSqMi']),
      "| with crime:", sum(1 for v in facts.values() if v['crimeByCategory2025']))
print("sample Suffolk:", json.dumps(facts.get("Suffolk"), ensure_ascii=False)[:300])
