// AUTO-GENERATED by backend/research_pipeline/temp/gen_force_facts.py
// Per-force land area (sq mi, from ONS PFA24 LSOA-joined shapefile, EPSG:27700)
// and observed 2025 crime counts by category (police.uk street_from_2021 parquet).
export interface ForceFacts {
  areaSqMi: number | null;
  crimeByCategory2025: Record<string, number>;
}

export const forceFacts: Record<string, ForceFacts> = {
  "Avon & Somerset": {
    "areaSqMi": 1847,
    "crimeByCategory2025": {
      "Bicycle theft": 1456,
      "Burglary": 6338,
      "Criminal damage and arson": 12022,
      "Drugs": 3526,
      "Other crime": 3246,
      "Other theft": 12871,
      "Possession of weapons": 947,
      "Public order": 17806,
      "Robbery": 2306,
      "Shoplifting": 14937,
      "Theft from the person": 444,
      "Vehicle crime": 6624,
      "Violence and sexual offences": 69668
    }
  },
  "Bedfordshire": {
    "areaSqMi": 474,
    "crimeByCategory2025": {
      "Bicycle theft": 560,
      "Burglary": 1958,
      "Criminal damage and arson": 4190,
      "Drugs": 2288,
      "Other crime": 1353,
      "Other theft": 3849,
      "Possession of weapons": 665,
      "Public order": 4077,
      "Robbery": 693,
      "Shoplifting": 4819,
      "Theft from the person": 405,
      "Vehicle crime": 4586,
      "Violence and sexual offences": 20742
    }
  },
  "Cambridgeshire": {
    "areaSqMi": 1312,
    "crimeByCategory2025": {
      "Bicycle theft": 1649,
      "Burglary": 2984,
      "Criminal damage and arson": 6480,
      "Drugs": 2729,
      "Other crime": 2218,
      "Other theft": 5003,
      "Possession of weapons": 1130,
      "Public order": 4637,
      "Robbery": 554,
      "Shoplifting": 7194,
      "Theft from the person": 694,
      "Vehicle crime": 3649,
      "Violence and sexual offences": 29020
    }
  },
  "Cheshire": {
    "areaSqMi": 904,
    "crimeByCategory2025": {
      "Bicycle theft": 626,
      "Burglary": 2558,
      "Criminal damage and arson": 5339,
      "Drugs": 3545,
      "Other crime": 2049,
      "Other theft": 4660,
      "Possession of weapons": 812,
      "Public order": 8874,
      "Robbery": 439,
      "Shoplifting": 5181,
      "Theft from the person": 275,
      "Vehicle crime": 2078,
      "Violence and sexual offences": 37263
    }
  },
  "City of London": {
    "areaSqMi": 1,
    "crimeByCategory2025": {
      "Bicycle theft": 268,
      "Burglary": 436,
      "Criminal damage and arson": 299,
      "Drugs": 391,
      "Other crime": 99,
      "Other theft": 1706,
      "Possession of weapons": 48,
      "Public order": 606,
      "Robbery": 215,
      "Shoplifting": 1354,
      "Theft from the person": 1104,
      "Vehicle crime": 91,
      "Violence and sexual offences": 1466
    }
  },
  "Cleveland": {
    "areaSqMi": 231,
    "crimeByCategory2025": {
      "Bicycle theft": 465,
      "Burglary": 3595,
      "Criminal damage and arson": 8750,
      "Drugs": 3040,
      "Other crime": 2765,
      "Other theft": 4174,
      "Possession of weapons": 729,
      "Public order": 5819,
      "Robbery": 1264,
      "Shoplifting": 8797,
      "Theft from the person": 278,
      "Vehicle crime": 3298,
      "Violence and sexual offences": 28813
    }
  },
  "Cumbria": {
    "areaSqMi": 2622,
    "crimeByCategory2025": {
      "Bicycle theft": 244,
      "Burglary": 1012,
      "Criminal damage and arson": 3839,
      "Drugs": 1842,
      "Other crime": 1120,
      "Other theft": 2276,
      "Possession of weapons": 561,
      "Public order": 3951,
      "Robbery": 132,
      "Shoplifting": 2477,
      "Theft from the person": 150,
      "Vehicle crime": 712,
      "Violence and sexual offences": 17894
    }
  },
  "Derbyshire": {
    "areaSqMi": 1015,
    "crimeByCategory2025": {
      "Bicycle theft": 405,
      "Burglary": 3039,
      "Criminal damage and arson": 7237,
      "Drugs": 3230,
      "Other crime": 1994,
      "Other theft": 5875,
      "Possession of weapons": 999,
      "Public order": 9127,
      "Robbery": 710,
      "Shoplifting": 7174,
      "Theft from the person": 594,
      "Vehicle crime": 3761,
      "Violence and sexual offences": 40132
    }
  },
  "Devon & Cornwall": {
    "areaSqMi": 3947,
    "crimeByCategory2025": {
      "Bicycle theft": 652,
      "Burglary": 3461,
      "Criminal damage and arson": 12965,
      "Drugs": 4076,
      "Other crime": 2972,
      "Other theft": 9630,
      "Possession of weapons": 1597,
      "Public order": 8640,
      "Robbery": 697,
      "Shoplifting": 9958,
      "Theft from the person": 844,
      "Vehicle crime": 3028,
      "Violence and sexual offences": 60913
    }
  },
  "Dorset": {
    "areaSqMi": 1019,
    "crimeByCategory2025": {
      "Bicycle theft": 584,
      "Burglary": 2042,
      "Criminal damage and arson": 4155,
      "Drugs": 1010,
      "Other crime": 570,
      "Other theft": 3604,
      "Possession of weapons": 335,
      "Public order": 2838,
      "Robbery": 358,
      "Shoplifting": 4702,
      "Theft from the person": 251,
      "Vehicle crime": 2775,
      "Violence and sexual offences": 18745
    }
  },
  "Durham": {
    "areaSqMi": 938,
    "crimeByCategory2025": {
      "Bicycle theft": 256,
      "Burglary": 2709,
      "Criminal damage and arson": 8510,
      "Drugs": 1504,
      "Other crime": 2305,
      "Other theft": 3446,
      "Possession of weapons": 535,
      "Public order": 4613,
      "Robbery": 331,
      "Shoplifting": 6871,
      "Theft from the person": 242,
      "Vehicle crime": 2317,
      "Violence and sexual offences": 25793
    }
  },
  "Essex": {
    "areaSqMi": 1407,
    "crimeByCategory2025": {
      "Bicycle theft": 1143,
      "Burglary": 5202,
      "Criminal damage and arson": 12522,
      "Drugs": 6380,
      "Other crime": 3484,
      "Other theft": 10107,
      "Possession of weapons": 1658,
      "Public order": 10750,
      "Robbery": 1351,
      "Shoplifting": 13525,
      "Theft from the person": 1016,
      "Vehicle crime": 10434,
      "Violence and sexual offences": 63964
    }
  },
  "Gloucestershire": {
    "areaSqMi": 1023,
    "crimeByCategory2025": {
      "Bicycle theft": 621,
      "Burglary": 2202,
      "Criminal damage and arson": 3674,
      "Drugs": 1199,
      "Other crime": 1433,
      "Other theft": 3334,
      "Possession of weapons": 470,
      "Public order": 3940,
      "Robbery": 525,
      "Shoplifting": 4476,
      "Theft from the person": 206,
      "Vehicle crime": 2281,
      "Violence and sexual offences": 20395
    }
  },
  "Greater Manchester": {
    "areaSqMi": 492,
    "crimeByCategory2025": {}
  },
  "Hampshire": {
    "areaSqMi": 1593,
    "crimeByCategory2025": {
      "Bicycle theft": 1441,
      "Burglary": 5419,
      "Criminal damage and arson": 11276,
      "Drugs": 4924,
      "Other crime": 3020,
      "Other theft": 9599,
      "Possession of weapons": 2492,
      "Public order": 13342,
      "Robbery": 1325,
      "Shoplifting": 14069,
      "Theft from the person": 846,
      "Vehicle crime": 6581,
      "Violence and sexual offences": 72844
    }
  },
  "Hertfordshire": {
    "areaSqMi": 634,
    "crimeByCategory2025": {
      "Bicycle theft": 909,
      "Burglary": 3833,
      "Criminal damage and arson": 6885,
      "Drugs": 2940,
      "Other crime": 1978,
      "Other theft": 8556,
      "Possession of weapons": 865,
      "Public order": 5580,
      "Robbery": 1068,
      "Shoplifting": 8728,
      "Theft from the person": 987,
      "Vehicle crime": 6019,
      "Violence and sexual offences": 36077
    }
  },
  "Humberside": {
    "areaSqMi": 1353,
    "crimeByCategory2025": {
      "Bicycle theft": 1184,
      "Burglary": 4285,
      "Criminal damage and arson": 8402,
      "Drugs": 2340,
      "Other crime": 2698,
      "Other theft": 5990,
      "Possession of weapons": 837,
      "Public order": 8685,
      "Robbery": 830,
      "Shoplifting": 8936,
      "Theft from the person": 329,
      "Vehicle crime": 3316,
      "Violence and sexual offences": 38346
    }
  },
  "Kent": {
    "areaSqMi": 1435,
    "crimeByCategory2025": {
      "Bicycle theft": 1011,
      "Burglary": 4670,
      "Criminal damage and arson": 16205,
      "Drugs": 6278,
      "Other crime": 5150,
      "Other theft": 11627,
      "Possession of weapons": 1782,
      "Public order": 7659,
      "Robbery": 1308,
      "Shoplifting": 16596,
      "Theft from the person": 748,
      "Vehicle crime": 7407,
      "Violence and sexual offences": 66180
    }
  },
  "Lancashire": {
    "areaSqMi": 1181,
    "crimeByCategory2025": {
      "Anti-social behaviour": 1,
      "Bicycle theft": 928,
      "Burglary": 5713,
      "Criminal damage and arson": 12485,
      "Drugs": 4018,
      "Other crime": 4263,
      "Other theft": 9052,
      "Possession of weapons": 1748,
      "Public order": 8187,
      "Robbery": 1184,
      "Shoplifting": 9288,
      "Theft from the person": 664,
      "Vehicle crime": 6464,
      "Violence and sexual offences": 60389
    }
  },
  "Leicestershire": {
    "areaSqMi": 986,
    "crimeByCategory2025": {
      "Bicycle theft": 1209,
      "Burglary": 4381,
      "Criminal damage and arson": 8942,
      "Drugs": 2902,
      "Other crime": 2258,
      "Other theft": 6641,
      "Possession of weapons": 773,
      "Public order": 9291,
      "Robbery": 858,
      "Shoplifting": 8187,
      "Theft from the person": 825,
      "Vehicle crime": 5958,
      "Violence and sexual offences": 36683
    }
  },
  "Lincolnshire": {
    "areaSqMi": 2292,
    "crimeByCategory2025": {
      "Bicycle theft": 546,
      "Burglary": 2228,
      "Criminal damage and arson": 5317,
      "Drugs": 1169,
      "Other crime": 1811,
      "Other theft": 3628,
      "Possession of weapons": 435,
      "Public order": 3915,
      "Robbery": 450,
      "Shoplifting": 6655,
      "Theft from the person": 123,
      "Vehicle crime": 2071,
      "Violence and sexual offences": 24069
    }
  },
  "Merseyside": {
    "areaSqMi": 246,
    "crimeByCategory2025": {
      "Bicycle theft": 1137,
      "Burglary": 4145,
      "Criminal damage and arson": 12526,
      "Drugs": 13828,
      "Other crime": 3782,
      "Other theft": 8051,
      "Possession of weapons": 1471,
      "Public order": 15457,
      "Robbery": 1483,
      "Shoplifting": 9719,
      "Theft from the person": 792,
      "Vehicle crime": 5154,
      "Violence and sexual offences": 59846
    }
  },
  "Metropolitan Police": {
    "areaSqMi": 608,
    "crimeByCategory2025": {
      "Bicycle theft": 13826,
      "Burglary": 47684,
      "Criminal damage and arson": 54613,
      "Drugs": 52486,
      "Other crime": 13149,
      "Other theft": 100243,
      "Possession of weapons": 5692,
      "Public order": 55756,
      "Robbery": 31332,
      "Shoplifting": 86774,
      "Theft from the person": 85420,
      "Vehicle crime": 84205,
      "Violence and sexual offences": 269756
    }
  },
  "Norfolk": {
    "areaSqMi": 2070,
    "crimeByCategory2025": {
      "Bicycle theft": 757,
      "Burglary": 1885,
      "Criminal damage and arson": 5964,
      "Drugs": 1751,
      "Other crime": 1971,
      "Other theft": 4033,
      "Possession of weapons": 793,
      "Public order": 4560,
      "Robbery": 436,
      "Shoplifting": 5707,
      "Theft from the person": 379,
      "Vehicle crime": 1557,
      "Violence and sexual offences": 27758
    }
  },
  "North Yorkshire": {
    "areaSqMi": 3212,
    "crimeByCategory2025": {
      "Bicycle theft": 839,
      "Burglary": 2092,
      "Criminal damage and arson": 4611,
      "Drugs": 1687,
      "Other crime": 1098,
      "Other theft": 3137,
      "Possession of weapons": 508,
      "Public order": 3054,
      "Robbery": 382,
      "Shoplifting": 5196,
      "Theft from the person": 162,
      "Vehicle crime": 1645,
      "Violence and sexual offences": 20206
    }
  },
  "Northamptonshire": {
    "areaSqMi": 914,
    "crimeByCategory2025": {
      "Bicycle theft": 386,
      "Burglary": 2779,
      "Criminal damage and arson": 4543,
      "Drugs": 2713,
      "Other crime": 1353,
      "Other theft": 4058,
      "Possession of weapons": 1047,
      "Public order": 4035,
      "Robbery": 1010,
      "Shoplifting": 6863,
      "Theft from the person": 199,
      "Vehicle crime": 3402,
      "Violence and sexual offences": 25372
    }
  },
  "Northumbria": {
    "areaSqMi": 2142,
    "crimeByCategory2025": {
      "Bicycle theft": 952,
      "Burglary": 6656,
      "Criminal damage and arson": 15138,
      "Drugs": 4691,
      "Other crime": 5405,
      "Other theft": 9778,
      "Possession of weapons": 1526,
      "Public order": 13128,
      "Robbery": 1887,
      "Shoplifting": 17898,
      "Theft from the person": 903,
      "Vehicle crime": 6324,
      "Violence and sexual offences": 56499
    }
  },
  "Nottinghamshire": {
    "areaSqMi": 835,
    "crimeByCategory2025": {
      "Bicycle theft": 1080,
      "Burglary": 4021,
      "Criminal damage and arson": 10113,
      "Drugs": 3926,
      "Other crime": 3873,
      "Other theft": 7570,
      "Possession of weapons": 1694,
      "Public order": 7247,
      "Robbery": 1529,
      "Shoplifting": 13855,
      "Theft from the person": 1014,
      "Vehicle crime": 5201,
      "Violence and sexual offences": 38639
    }
  },
  "South Yorkshire": {
    "areaSqMi": 598,
    "crimeByCategory2025": {
      "Bicycle theft": 813,
      "Burglary": 7366,
      "Criminal damage and arson": 13396,
      "Drugs": 5228,
      "Other crime": 5552,
      "Other theft": 8585,
      "Possession of weapons": 1892,
      "Public order": 12309,
      "Robbery": 1920,
      "Shoplifting": 13376,
      "Theft from the person": 969,
      "Vehicle crime": 10433,
      "Violence and sexual offences": 55547
    }
  },
  "Staffordshire": {
    "areaSqMi": 1051,
    "crimeByCategory2025": {
      "Bicycle theft": 688,
      "Burglary": 3611,
      "Criminal damage and arson": 7238,
      "Drugs": 3068,
      "Other crime": 2339,
      "Other theft": 5816,
      "Possession of weapons": 1184,
      "Public order": 8437,
      "Robbery": 1037,
      "Shoplifting": 6979,
      "Theft from the person": 236,
      "Vehicle crime": 4674,
      "Violence and sexual offences": 41161
    }
  },
  "Suffolk": {
    "areaSqMi": 1467,
    "crimeByCategory2025": {
      "Bicycle theft": 428,
      "Burglary": 1701,
      "Criminal damage and arson": 4397,
      "Drugs": 1371,
      "Other crime": 1499,
      "Other theft": 3278,
      "Possession of weapons": 679,
      "Public order": 3178,
      "Robbery": 263,
      "Shoplifting": 3966,
      "Theft from the person": 259,
      "Vehicle crime": 1946,
      "Violence and sexual offences": 20929
    }
  },
  "Surrey": {
    "areaSqMi": 644,
    "crimeByCategory2025": {
      "Bicycle theft": 656,
      "Burglary": 3115,
      "Criminal damage and arson": 6862,
      "Drugs": 3012,
      "Other crime": 2224,
      "Other theft": 5877,
      "Possession of weapons": 778,
      "Public order": 8220,
      "Robbery": 580,
      "Shoplifting": 6210,
      "Theft from the person": 499,
      "Vehicle crime": 4300,
      "Violence and sexual offences": 30866
    }
  },
  "Sussex": {
    "areaSqMi": 1463,
    "crimeByCategory2025": {
      "Bicycle theft": 1377,
      "Burglary": 4549,
      "Criminal damage and arson": 11715,
      "Drugs": 5000,
      "Other crime": 3374,
      "Other theft": 9800,
      "Possession of weapons": 2396,
      "Public order": 12579,
      "Robbery": 1573,
      "Shoplifting": 19718,
      "Theft from the person": 1024,
      "Vehicle crime": 5205,
      "Violence and sexual offences": 50897
    }
  },
  "Thames Valley": {
    "areaSqMi": 2220,
    "crimeByCategory2025": {
      "Bicycle theft": 2858,
      "Burglary": 6558,
      "Criminal damage and arson": 13788,
      "Drugs": 5939,
      "Other crime": 3697,
      "Other theft": 14971,
      "Possession of weapons": 1241,
      "Public order": 14792,
      "Robbery": 2028,
      "Shoplifting": 18503,
      "Theft from the person": 1830,
      "Vehicle crime": 10998,
      "Violence and sexual offences": 72527
    }
  },
  "Warwickshire": {
    "areaSqMi": 762,
    "crimeByCategory2025": {
      "Bicycle theft": 320,
      "Burglary": 2109,
      "Criminal damage and arson": 3418,
      "Drugs": 1050,
      "Other crime": 1281,
      "Other theft": 2868,
      "Possession of weapons": 583,
      "Public order": 3362,
      "Robbery": 496,
      "Shoplifting": 3798,
      "Theft from the person": 223,
      "Vehicle crime": 3444,
      "Violence and sexual offences": 17100
    }
  },
  "West Mercia": {
    "areaSqMi": 2859,
    "crimeByCategory2025": {
      "Bicycle theft": 734,
      "Burglary": 4063,
      "Criminal damage and arson": 7600,
      "Drugs": 2450,
      "Other crime": 2358,
      "Other theft": 6296,
      "Possession of weapons": 1098,
      "Public order": 6673,
      "Robbery": 805,
      "Shoplifting": 9000,
      "Theft from the person": 336,
      "Vehicle crime": 3627,
      "Violence and sexual offences": 38320
    }
  },
  "West Midlands": {
    "areaSqMi": 348,
    "crimeByCategory2025": {
      "Bicycle theft": 1819,
      "Burglary": 14420,
      "Criminal damage and arson": 24693,
      "Drugs": 9329,
      "Other crime": 6430,
      "Other theft": 18934,
      "Possession of weapons": 6645,
      "Public order": 17525,
      "Robbery": 6533,
      "Shoplifting": 32206,
      "Theft from the person": 2647,
      "Vehicle crime": 27060,
      "Violence and sexual offences": 131386
    }
  },
  "West Yorkshire": {
    "areaSqMi": 784,
    "crimeByCategory2025": {
      "Bicycle theft": 1565,
      "Burglary": 14131,
      "Criminal damage and arson": 20531,
      "Drugs": 9949,
      "Other crime": 9078,
      "Other theft": 18836,
      "Possession of weapons": 2565,
      "Public order": 25042,
      "Robbery": 3660,
      "Shoplifting": 21006,
      "Theft from the person": 2345,
      "Vehicle crime": 15476,
      "Violence and sexual offences": 126331
    }
  },
  "Wiltshire": {
    "areaSqMi": 1346,
    "crimeByCategory2025": {
      "Bicycle theft": 502,
      "Burglary": 1659,
      "Criminal damage and arson": 4268,
      "Drugs": 1305,
      "Other crime": 1219,
      "Other theft": 2688,
      "Possession of weapons": 450,
      "Public order": 4063,
      "Robbery": 239,
      "Shoplifting": 4011,
      "Theft from the person": 273,
      "Vehicle crime": 1691,
      "Violence and sexual offences": 19561
    }
  }
};
